# Generated by Django 4.2.6 on 2023-10-18 01:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Passenger",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("last_name", models.CharField(max_length=30)),
                ("first_name", models.CharField(max_length=30)),
                ("patronymic", models.CharField(blank=True, max_length=30, null=True)),
                (
                    "gender",
                    models.BooleanField(
                        choices=[(True, "Мужской"), (False, "Женский")], default=True
                    ),
                ),
                ("age", models.IntegerField()),
                ("about", models.CharField(max_length=250)),
                ("contact", models.CharField(max_length=40)),
                ("cluster", models.IntegerField(blank=True, null=True)),
                (
                    "trip_with_child",
                    models.IntegerField(
                        choices=[
                            (0, "Еду один"),
                            (1, "Один ребенок"),
                            (2, "Двое детей"),
                            (3, "Трое детей"),
                            (4, "Четверо детей"),
                            (5, "Пятеро детей"),
                        ],
                        default=0,
                    ),
                ),
                ("trip_with_animals", models.BooleanField(default=False)),
                (
                    "regular_choice",
                    models.IntegerField(
                        choices=[(1, "Плацкарт"), (2, "Купе"), (3, "СВ"), (4, "Люкс")]
                    ),
                ),
                (
                    "smoking_attitude",
                    models.IntegerField(
                        choices=[
                            (1, "Крайне негативно"),
                            (2, "Негативно"),
                            (3, "Нейтрально"),
                            (4, "Положительно"),
                            (5, "Крайне положительно"),
                        ]
                    ),
                ),
                (
                    "having_children",
                    models.IntegerField(choices=[(1, "Да"), (0, "Нет")]),
                ),
                (
                    "sociability",
                    models.IntegerField(
                        choices=[
                            (1, "Предпочитаю не общаться в поездке"),
                            (2, "Редко общаюсь"),
                            (3, "По-настроению"),
                            (4, "Часто общаюсь"),
                            (5, "Люблю заводить новые знакомства в поездах"),
                        ]
                    ),
                ),
                (
                    "pets_attitude",
                    models.IntegerField(
                        choices=[(1, "Положительно"), (0, "Отрицательно")]
                    ),
                ),
                (
                    "django_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Seat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price", models.IntegerField(null=True)),
                ("seat_number", models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Train",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("place1", models.CharField(max_length=30)),
                ("place2", models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name="VanCharacter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.IntegerField(
                        choices=[(1, "Плацкарт"), (2, "Купе"), (3, "СВ"), (4, "Люкс")]
                    ),
                ),
                (
                    "class_van",
                    models.IntegerField(
                        choices=[
                            (1, "3Б"),
                            (2, "3Э"),
                            (3, "2Т"),
                            (4, "2Э"),
                            (5, "1Э"),
                            (6, "1Т"),
                            (7, "1М"),
                        ]
                    ),
                ),
                ("seat_quantity", models.IntegerField()),
                ("food", models.BooleanField()),
                ("info_entertaiment", models.BooleanField()),
                ("linen", models.BooleanField()),
                ("biotoilet", models.BooleanField()),
                ("conditioner", models.BooleanField()),
                ("cosmetic", models.BooleanField()),
                ("press", models.BooleanField()),
                ("pet", models.BooleanField()),
                ("bath", models.BooleanField()),
                ("business_lounge", models.BooleanField()),
                ("taxi", models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name="Van",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="rzd_app.vancharacter",
                    ),
                ),
                (
                    "train",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="rzd_app.train"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Trip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("finished", models.BooleanField(default=False)),
                ("with_children", models.IntegerField(default=0)),
                ("with_animals", models.BooleanField(default=False)),
                (
                    "passenger",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="rzd_app.passenger",
                    ),
                ),
                (
                    "seats",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="rzd_app.seat"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="seat",
            name="van",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="rzd_app.van"
            ),
        ),
    ]
