# Generated by Django 4.2.6 on 2023-10-17 00:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rzd_app", "0010_auto_20231015_1137"),
    ]

    operations = [
        migrations.AddField(
            model_name="passenger",
            name="cluster",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="passenger",
            name="gender",
            field=models.BooleanField(
                choices=[(True, "Мужской"), (False, "Женский")], default=True
            ),
        ),
    ]
